### ISSUE TITLE
Upgrading to Moodle v4.0 (from v3.9) with mod_pulse raises issues with class 'format base'.

### ISSUE THREAD

**Issue by haasdijk** [bdecentgmbh/moodle-mod_pulse#10]
After upgrading a Moodle v3.9 installation to Moodle v4.0, the mod_pulse plugin uses almost all the memory on the server. Once I remove the plugin the load is as expected.
I then reinstalled the plugin and tried to restore the courses that use this plugin. I got an 'allowed memory size error'.

There is 1 course that contains mod_pulse AND is accessible after the upgrade. This one gives the following debug output when opened:
Class 'format_base' has been renamed for the autoloader and is now deprecated. Please use 'core_courseformat\base' instead.

    line 142 of /lib/classes/component.php: call to debugging()
    line ? of unknownfile: call to core_component::classloader()
    line 43 of /course/format/tiles/lib.php: call to spl_autoload_call()
    line 865 of /lib/classes/component.php: call to include_once()
    line 7852 of /lib/moodlelib.php: call to core_component::get_plugin_list_with_file()
    line 1253 of /mod/pulse/lib.php: call to get_plugins_with_function()
    line 948 of /mod/pulse/lib.php: call to pulse_extend_reaction()
    line 1570 of /mod/pulse/lib.php: call to mod_pulse_cm_completionbuttons()
    line 2474 of /lib/modinfolib.php: call to mod_pulse_cm_info_view()
    line 2506 of /lib/modinfolib.php: call to cm_info->call_mod_function()
    line 1742 of /lib/modinfolib.php: call to cm_info->obtain_view_data()
    line 1555 of /lib/modinfolib.php: call to cm_info->get_extra_classes()
    line 106 of /course/format/classes/output/local/content/section/cmitem.php: call to cm_info->__get()
    line 122 of /course/format/classes/output/local/content/section/cmlist.php: call to core_courseformat\output\local\content\section\cmitem->export_for_template()
    line 225 of /course/format/classes/output/local/content/section.php: call to core_courseformat\output\local\content\section\cmlist->export_for_template()
    line 156 of /course/format/classes/output/local/content/section.php: call to core_courseformat\output\local\content\section->add_cm_data()
    line 46 of /course/format/topics/classes/output/courseformat/content/section.php: call to core_courseformat\output\local\content\section->export_for_template()
    line 160 of /course/format/classes/output/local/content.php: call to format_topics\output\courseformat\content\section->export_for_template()
    line 86 of /course/format/classes/output/local/content.php: call to core_courseformat\output\local\content->export_sections()
    line 500 of /lib/outputrenderers.php: call to core_courseformat\output\local\content->export_for_template()
    line 108 of /course/format/classes/output/section_renderer.php: call to plugin_renderer_base->render()
    line 60 of /course/format/topics/format.php: call to core_courseformat\output\section_renderer->render()
    line 270 of /course/view.php: call to require()

Other pages, for example /admin/search.php and /backup/restorfile.php give a few extra lines for the courseformat tiles. All for the deprecated class.

I have temporarily removed all courses with mod_pulse, except for the course that appears to be accessible. In /report/status I get Fail delays: 1 day - mod_pulse\task\sendinvitation ID = 239565

Restoring a course with mod_pulse gives the warning:
Technical information and warnings
setting controller status to 800
saving controller to db
calculating controller checksum 2708398ba4f988b6d78d93e94e26a0c6

The error message when opening the course right after I restore it is:
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 16384 bytes) in /home/moodle/domains/t2.kwadraad.nl/public_html/lib/dml/mysqli_native_moodle_database.php on line 1277

**Comment by stefanscholz** [comment]
Morning @haasdijk ,

Sorry to hear that you have issues with Pulse.

Pulse is not a format, so the error you mentioned about the deprecated format_base is more likely to relate to the format you're using (apparently tiles). Have you upgraded the format already to a 4.0 compatible version?

Depending on the size of your site, pulse can indeed require a substantial amount of memory in our experience. A bit simplified, pulse needs to determine the availability for all of its instances for all users (of a course). If you have many students in a course, that can lead to high load.

Have you been monitoring your server prior to the upgrade in this regard? I mean, did pulse use a similar amount of memory?

You could try the latest version here on GitHub (1.12), which introduces two features in order to reduce the load: 1) limit how much is processed in one run, and 2) print less information in the cron log.

Both helped on other sites with substantial user count.

I have never experienced though that a site or a whole course is no longer working, the load introduced by pulse is only by the cron job, I.e. it might be something else (which could still be related to pulse) that causes the issues.

Hope this helps!
Stefan

**Comment by haasdijk** [comment]
Stefan,

I got the latest version mod_pulse from GitHub and installed it. Upgraded Moodle V4.0 to the latest build aswell. I can now restore and load the courses. In System status I still have 6 task(s) failing but they will disappear at some point (?).
The error message regarding the deprecated remains. But that has nothing to do with mod_pulse.
Thanks for your help.
